build: minify workflows

diff --git a/.github/workflows/deploy-and-purge-cache.yaml b/.github/workflows/deploy-and-purge-cache.yaml
--- a/.github/workflows/deploy-and-purge-cache.yaml
+++ b/.github/workflows/deploy-and-purge-cache.yaml
@@ -47,3 +47,26 @@ jobs:
       with:
         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+
+    - name: Purge cache
+      env:
+        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
+        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+      run: |
+        HTTP_RESPONSE=$(curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
+          -H "Content-Type: application/json" \
+          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
+          -w "HTTP_STATUS:%{http_code}" \
+          -d '{"hosts":["xeonzilla.top"]}')
+
+        HTTP_BODY=$(echo "${HTTP_RESPONSE}" | sed -E 's/HTTP_STATUS\:[0-9]{3}$//')
+        HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | tr -d '\n' | sed -E 's/.*HTTP_STATUS:([0-9]{3})$/\1/')
+
+        if [ "${HTTP_STATUS}" -eq "200" ]; then
+          echo "Successfully purged!"
+          exit 0
+        else
+          echo "Purge failed!"
+          echo "${HTTP_BODY}"
+          exit 1
+        fi
